### ISSUE TITLE
MIUI 9 PROBLEM

### ISSUE THREAD

**Issue by hadiyarajesh** [Ty3uK/extMIUI#1]
extMIUI is not working in miui 9. It force close with an error following error :

java.lang.RuntimeException: Unable to start activity ComponentInfo{tk.ty3uk.extmiuiv7/tk.ty3uk.extmiuiv7.ui.StartActivity}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6342)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
	at android.app.ContextImpl.checkMode(ContextImpl.java:2176)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:373)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:368)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
	at android.support.v7.preference.t.b(SourceFile:290)
	at android.support.v7.preference.Preference.I(SourceFile:1018)
	at android.support.v7.preference.Preference.f(SourceFile:1322)
	at android.support.v7.preference.Preference.a(SourceFile:1098)
	at android.support.v7.preference.Preference.a(SourceFile:1109)
	at android.support.v7.preference.PreferenceGroup.d(SourceFile:191)
	at android.support.v7.preference.PreferenceGroup.c(SourceFile:123)
	at android.support.v7.preference.s.a(SourceFile:360)
	at android.support.v7.preference.s.a(SourceFile:167)
	at android.support.v7.preference.s.a(SourceFile:117)
	at android.support.v7.preference.t.a(SourceFile:122)
	at android.support.v7.preference.m.a(SourceFile:441)
	at tk.ty3uk.extmiuiv7.ui.n.a(SourceFile:24)
	at android.support.v7.preference.m.a(SourceFile:220)
	at android.support.v4.b.r.j(SourceFile:2068)
	at android.support.v4.b.z.a(SourceFile:1055)
	at android.support.v4.b.h.b(SourceFile:838)
	at android.support.v4.b.h.b(SourceFile:878)
	at android.support.v4.b.h.run(SourceFile:719)
	at android.support.v4.b.z.e(SourceFile:1677)
	at android.support.v4.b.w.n(SourceFile:388)
	at android.support.v4.b.t.onStart(SourceFile:604)
	at android.support.v7.a.p.onStart(SourceFile:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6873)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)

**Comment by hadiyarajesh** [comment]
Only happens in android nougat base MIUI.
